# Generated by Django 4.2.23 on 2025-07-08 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='watch_later',
            field=models.ManyToManyField(blank=True, related_name='watch_later_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
